# Laboratorio de regresión - 3

## Significancia de factores

|                |   |
:----------------|---|
| **Nombre**     | Eugenio Hernández Aranda  |
| **Fecha**      | 03/02/2026  |
| **Expediente** | 756225  |

Descarga el archivo de publicidad y carga los datos (Advertising.csv).

In [1]:
from google.colab import files
eugenio= files.upload()

Saving Advertising.csv to Advertising.csv


In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np


In [3]:
df= pd.read_csv('Advertising.csv')
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

**¿Hay alguna relación entre el presupuesto para publicidad y las ventas?**

Nuestra primera meta debe ser determinar si hay evidencia en los datos de que haya una asociación entre estas variables.

- ¿Por qué? ¿Qué resultaría si nos diéramos cuenta de la falta de relación entre el presupuesto de publicidad y las ventas?

Si nos dieramos cuenta que lo que se le invierte de publicidad a las ventas no tiene correlación con que realmente se vende, no tendría sentido seguir invirtiendo en publicidad.

**¿Qué tan fuerte es esta relación?**
Asumiendo que existe esta relación, ¿nos sirve conocer el impacto que tiene invertir en publicidad en las ventas?

Sí nos serviría saberlo, ya que así podríamos saber cuanto nos conviene invertirle a la publicidad.

**¿Cuáles medios están asociados con las ventas? ¿Qué tan grande es la asociación entre un medio específico y las ventas?**

Hay 3 medios distintos en los datos. ¿Sirve invertir en los 3? ¿Conviene más invertir sólo en uno?

**¿Qué tan seguros estamos de que podríamos predecir ventas futuras?**

**¿La relación es lineal?**

**¿Hay sinergia entre estos medios?**

Puede ser que gastar \\$50,000 en publicidad y otros \\$50,000 en radio es mejor opción que gastar \\$100,000 en televisión. A esto le llamamos efecto de interacción.

Podemos usar regresión lineal para responder todas estas preguntas.

Realiza una regresión lineal:

$$ \text{ventas} \approx \beta_0 + (\beta_1)(\text{TV})$$

In [4]:
TV= df['TV'].to_numpy().reshape(-1,1)
y= df['sales'].to_numpy().reshape(-1,1)
TV

array([[230.1],
       [ 44.5],
       [ 17.2],
       [151.5],
       [180.8],
       [  8.7],
       [ 57.5],
       [120.2],
       [  8.6],
       [199.8],
       [ 66.1],
       [214.7],
       [ 23.8],
       [ 97.5],
       [204.1],
       [195.4],
       [ 67.8],
       [281.4],
       [ 69.2],
       [147.3],
       [218.4],
       [237.4],
       [ 13.2],
       [228.3],
       [ 62.3],
       [262.9],
       [142.9],
       [240.1],
       [248.8],
       [ 70.6],
       [292.9],
       [112.9],
       [ 97.2],
       [265.6],
       [ 95.7],
       [290.7],
       [266.9],
       [ 74.7],
       [ 43.1],
       [228. ],
       [202.5],
       [177. ],
       [293.6],
       [206.9],
       [ 25.1],
       [175.1],
       [ 89.7],
       [239.9],
       [227.2],
       [ 66.9],
       [199.8],
       [100.4],
       [216.4],
       [182.6],
       [262.7],
       [198.9],
       [  7.3],
       [136.2],
       [210.8],
       [210.7],
       [ 53.5],
       [261.3],
       [

In [5]:
lr=LinearRegression()
lr.fit(TV,y)
B0 = lr.intercept_
B1 = lr.coef_
print(f'{B0}, {B1}')

[7.03259355], [[0.04753664]]


In [ ]:
ventas_predict = B0+B1*TV
ventas_predict


### Verificando la precisión de nuestros coeficientes estimados

Recuerda que en el mundo real hay ruidos y errores de medición. Siempre se asume que la verdadera relación entre $X$ y $Y$ es $$Y = \beta_0 + \beta_1 X + \epsilon$$

Se asume que el término de error es independiente de $X$ (el error siempre es el mismo sin importar el valor de $X$). Este modelo describe a la *línea de regresión de la población*, que es la mejor aproximación de la verdadera relación entre $X$ y $Y$. Cuando usamos mínimos cuadrados encontramos la *línea de mínimos cuadrados*.

¿Cuál es la diferencia entre población y muestra?

La población se refiere a **todos** los individuos que comparten una cierta característica y de los cuales queremos hacer un análisis

La muestra se refiere a una parte o subconjunto que representa a la población

¿Cuál crees que sea la diferencia entre hacer una regresión con todos los datos de la población y una muestra de ella?

La diferencia es que con la población no son estimados, por lo que no tienes que calcular estimados, además de que no se necesita hacer pruebas de hipotesis o hacer intervalos de confianza, pero suele ser algo muy difícil de hacer por la cantidad de datos que hay dentro de una población.

En cambio para la muestra, con una parte de los datos se hacen predicciones, sin embargo como no tenemos los datos completos, las predicciones no son del todo precisas, y se tienen que hacer pruebas de hipótesis o pruebas de confianza para ver que tan acertada es la predicción

La línea de regresión de la población no se puede observar. El concepto de comparar estas líneas es una extensión natural del acercamiento estadístico estándar de usar información de una muestra para estimar características de una población grande.

Imagina que quieres encontrar la altura promedio de un mexicano $\mu$. Medir a todos y cada uno de los mexicanos en situaciones similares, con la misma regla, mismo operador, y otras incontables formas de minimizar la variación de la medida es una tarea imposible. Lo que podemos asumir es que $\hat{\mu} = \bar{y}$. La media poblacional y la media muestral son diferentes, pero la media muestral es usualmente un buen estimado.

De la misma manera, como no contamos con el 100% de la información para hacer una regresión, los coeficientes $\beta_0$ y $\beta_1$ son desconocidos. Podemos estimarlos usando mínimos cuadrados, encontrando $\hat{\beta_0}$ y $\hat{\beta_1}$. Puede que las muestras que tengamos en ese momento estén un poco por encima de la media, pero otras muestras en otro momento puede que estén debajo de la media. En general, esperamos que el promedio de las aproximaciones $\hat{\mu}$ aproxime a $\mu$.

Esto lleva a la pregunta: ¿qué tan cercanos son nuestros coeficientes estimados a los verdaderos coeficientes? Utilizamos el concepto de error estándar para evaluar esto.

$$ \text{Var}(\hat{\mu})=\text{SE}(\hat{\mu})^2 = \frac{\sigma^2}{n} $$

Donde $\sigma$ es la desviación estándar de cada una de las observaciones $y_i$ de $Y$. El error estándar nos dice la cantidad promedio que el estimado difiere del valor verdadero. Podemos ver en la fórmula que entre más observaciones tengamos el error se hace más pequeño. Las fórmulas para errores estándar de $\hat{\beta_0}$ y $\hat{\beta_1}$ son:

$$ \text{SE}(\hat{\beta_0})^2 = \sigma^2 [\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2}]$$

$$ \text{SE}(\hat{\beta_1})^2 = \frac{\sigma^2}{\sum_{i=1}^n (x_i - \bar{x})^2}$$

$$ \sigma^2 = \text{Var}(\epsilon) = \text{RSE}^2 = \frac{\text{RSS}}{n-p}$$

Para que estas fórmulas sean validas asumimos que los errores $\epsilon_i$ tienen varianza común $\sigma^2$ y que no están correlacionados.

Calcula los errores estándar de los coeficientes

In [7]:
RSS = np.sum((y-lr.predict(TV))**2)
RSS

np.float64(2102.5305831313512)

In [8]:
sigma2= RSS/(len(y)-2)
sigma2

np.float64(10.618841328946218)

In [9]:
SE_0=sigma2*(1/len(y)+((np.mean(TV))**2)/(np.sum((TV-np.mean(TV))**2)))
SE_0=SE_0**.5
SE_0

np.float64(0.4578429402734785)

In [10]:
SE_1= sigma2/(np.sum((TV-np.mean(TV))**2))
SE_1 = SE_1**.5
SE_1

np.float64(0.0026906071877968707)

Estos errores se pueden usar para calcular intervalos de confianza. Un intervalo de confianza del $95\%$ se define como un rango de valores en el cuál se encuentra el desconocido valor verdadero con un $95\%$ de probabilidad.

Otra forma de verlo es que si tomamos muestras repetidas y construimos un intervalo de confianza para cada una, el $95\%$ de los intervalos creados van a contener el valor verdadero. Para la regresión el intervalo de confianza del $95\%$ toma la forma:

$$ \hat{\beta_j} \pm 2\text{SE}(\hat{\beta_j})$$

Calcula los intervalos de confianza para los coeficientes estimados:

In [11]:
def intervalos_confianza(b_j,SE_j):
  intervalo_bj= [b_j-2*SE_j,b_j+2*SE_j]
  return intervalo_bj

In [12]:
intervalos_confianza(B0,SE_0)

[array([6.11690767]), array([7.94827943])]

In [13]:
intervalos_confianza(B1,SE_1)

[array([[0.04215543]]), array([[0.05291785]])]

Los errores estándar también se usan para realizar pruebas de hipótesis. La prueba de hipótesis más común es probar la hipótesis nula de:

$$ H_0: \text{No hay relación entre } X \text{ y } Y \ \ \ \ (\beta_1=0)$$

contra la hipótesis alternativa:
$$ H_0: \text{Hay alguna relación entre } X \text{ y } Y \ \ \ (\beta_1 \neq 0)$$

Explica con tus palabras el significado de la hipótesis nula y la hipótesis alternativa.

Para probal la hipótesis nula debemos determinar si nuestro estimado $\hat{\beta_1}$ de $\beta_1$ está lo suficientemente alejado de cero para que podamos decir con confianza que este valor no es cero.

¿Qué tan lejos? Depende de qué tanta confianza tengamos en el estimado encontrado. Si nuestro error estándar es pequeño y nuestro estimado está alejado de cero podríamos decir que hay muy poca probabilidad de que el valor verdadero sea 0. En cambio, si nuestro error estándar es grande y nuestro estimado está muy cerca de cero, entonces podrías ser que el valor verdadero sea cero y que no haya relación entre las variables.

Se calcula un *estadístico t* dado por
$$ t = \frac{\hat{\beta_j} - \mu}{\text{SE}(\hat{\beta_j})} $$

donde $\mu$ es el valor contra el que queremos probar.

Calcula el estadístico t para tus coeficientes estimados, usando como referencia la prueba de hipótesis.

In [14]:
#hipotesis 1
miu=0
t1= (B0-miu)/(SE_0)
t1

array([15.36027517])

In [15]:
#hipotesis 2
miu=0
t2= (B1-miu)/(SE_1)
t2

array([[17.6676256]])

In [24]:
SE_0=sigma2*(1/len(y)+((np.mean(TV))**2)/(np.sum((TV-np.mean(TV))**2)))
SE_0=SE_0**.5
SE_0

np.float64(0.7154961801812062)

La distribución t tiene forma de campana y se parece bastante a la distribución normal cuando $n > 30$. Ya sólo es cuestión de calcular la probabilidad de observar cualquier número tal que su valor absoluto sea igual o mayor que el valor absoluto del estadístico t calculado. En otras palabras:
$$ P(|x| \geq |t|) $$

A esta probabilidad la llamamos *p-value*. Un *p-value* pequeño indica que es poco probable que exista por puro azar una relación significativa entre predictor y respuesta, en caso de que no haya una asociación real entre predictor y respuesta. En otras palabras, el *p-value* te dice la probabilidad de que parezca que hay relación cuando no la hay.

Si el *p-value* es pequeño, inferimos que sí hay una asociación entre el predictor y la respuesta, y **rechazamos la hipótesis nula**.
  

¿Qué tan pequeño? Depende de la aplicación. Un valor muy común es del $5\%$.

Utiliza el siguiente código para calcular el *p-value* para tus coeficientes

`from scipy import stats`

`p_bj = 2*(1 - stats.t.cdf(np.abs(t_bj), n-p))`

In [17]:
from scipy import stats
p= 2*(1 - stats.t.cdf(np.abs(t2), len(y)-2))
p


array([[0.]])

¿Se rechaza la hipótesis nula? ¿Qué significa?

Realiza otras dos regresiones. Ya tienes hecha la regresión de ventas dado el gasto en publicidad de TV. Realiza la regresión para gastos en radio y gastos en periódico. Organiza las respuestas para que debajo de esta celda se tenga:
- Título de regresión
- Coeficientes estimados
- Errores estándar de los coeficientes
- Intervalos de confianza
- Estadísticos t
- p-values
- Observaciones

Regresión NewsPaper

In [ ]:
NP= df['newspaper'].to_numpy().reshape(-1,1)
y= df['sales'].to_numpy().reshape(-1,1)
NP

In [21]:
lr.fit(NP,y)
B0 = lr.intercept_
B1 = lr.coef_


In [22]:
RSS = np.sum((y-lr.predict(NP))**2)
RSS

np.float64(5134.804544111939)

In [23]:
sigma2= RSS/(len(y)-2)
sigma2

np.float64(25.933356283393632)

In [30]:
SE_0=sigma2*(1/len(y)+((np.mean(TV))**2)/(np.sum((TV-np.mean(TV))**2)))
SE_0=SE_0**.5
SE_0

np.float64(0.7154961801812062)

In [25]:
SE_1= sigma2/(np.sum((TV-np.mean(TV))**2))
SE_1 = SE_1**.5
SE_1

np.float64(0.004204758872304217)

In [26]:
intervalos_confianza(B1,SE_1)

[array([[0.04628358]]), array([[0.06310262]])]

In [27]:
intervalos_confianza(B0,SE_0)

[array([10.92041471]), array([13.78239943])]

In [28]:
#hipotesis 1
miu=0
t1= (B0-miu)/(SE_0)
t1

array([17.2627156])

In [29]:
#hipotesis 2
miu=0
t2= (B1-miu)/(SE_1)
t2

array([[13.00742804]])

In [41]:
#p-values
p= 2*(1 - stats.t.cdf(np.abs(t2), len(y)-2))
p

array([[0.]])

Radio

In [31]:
Radio= df['radio'].to_numpy().reshape(-1,1)


In [32]:
lr.fit(Radio,y)
B0 = lr.intercept_
B1 = lr.coef_

In [33]:
RSS = np.sum((y-lr.predict(NP))**2)
RSS

np.float64(7632.586063008564)

In [34]:
sigma2= RSS/(len(y)-2)
sigma2

np.float64(38.54841445963921)

In [35]:
SE_0=sigma2*(1/len(y)+((np.mean(TV))**2)/(np.sum((TV-np.mean(TV))**2)))
SE_0=SE_0**.5
SE_0

np.float64(0.8723308188934985)

In [36]:
SE_1= sigma2/(np.sum((TV-np.mean(TV))**2))
SE_1 = SE_1**.5
SE_1

np.float64(0.005126429535092556)

In [37]:
intervalos_confianza(B1,SE_1)

[array([[0.19224292]]), array([[0.21274864]])]

In [38]:
intervalos_confianza(B0,SE_0)

[array([7.56697646]), array([11.05629973])]

In [39]:
#hipotesis 1
miu=0
t1= (B0-miu)/(SE_0)
t1

array([10.67443439])

In [40]:
#hipotesis 2
miu=0
t2= (B1-miu)/(SE_1)
t2

array([[39.50035439]])

In [42]:
p= 2*(1 - stats.t.cdf(np.abs(t2), len(y)-2))
p

array([[0.]])

## Regresión lineal múltiple

En lugar de hacer una regresión para cada factor independiente, quizás se puede extender el modelo para que tenga varios factores dentro:

$$ Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_p X_p + \epsilon $$

Para nuestro ejemplo de publicidad:

$$ \text{sales} = \beta_0 + \beta_1 (\text{TV}) + \beta_2 (\text{radio}) + \beta_3 (\text{newspaper}) + \epsilon $$

Utiliza la librería `statsmodels` para realizar la regresión. Por defecto la librería statsmodels no toma en cuenta el intercepto ($\beta_0$), por lo que se tendrá que agregar una columna de unos de tamaño *n* a la matriz X.

`import statsmodels.api as sm`

`ols = sm.OLS(Y, X)`

`results = ols.fit()`

`results.summary()`

In [43]:
import statsmodels.api as sm

In [10]:
ols = sm.OLS(y, X)
results = ols.fit()
results.summary()

In [44]:
TV2=sm.add_constant(TV) # -> Agrega la columna de 1 a la matriz
model=sm.OLS(y,TV2) # -> Modela minimos cuadrados ordinarios
results=model.fit() #-> Optimiza
print(results.summary()) # -> imprime resultados

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Tue, 03 Feb 2026   Prob (F-statistic):           1.47e-42
Time:                        19:45:21   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.0326      0.458     15.360      0.0

In [45]:
Radio2=sm.add_constant(Radio) # -> Agrega la columna de 1 a la matriz
model=sm.OLS(y,Radio2) # -> Modela minimos cuadrados ordinarios
results=model.fit() #-> Optimiza
print(results.summary()) # -> imprime resultados

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.332
Model:                            OLS   Adj. R-squared:                  0.329
Method:                 Least Squares   F-statistic:                     98.42
Date:                Tue, 03 Feb 2026   Prob (F-statistic):           4.35e-19
Time:                        19:45:40   Log-Likelihood:                -573.34
No. Observations:                 200   AIC:                             1151.
Df Residuals:                     198   BIC:                             1157.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          9.3116      0.563     16.542      0.0

In [46]:
NP2=sm.add_constant(NP) # -> Agrega la columna de 1 a la matriz
model=sm.OLS(y,NP2) # -> Modela minimos cuadrados ordinarios
results=model.fit() #-> Optimiza
print(results.summary()) # -> imprime resultados

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.052
Model:                            OLS   Adj. R-squared:                  0.047
Method:                 Least Squares   F-statistic:                     10.89
Date:                Tue, 03 Feb 2026   Prob (F-statistic):            0.00115
Time:                        19:46:03   Log-Likelihood:                -608.34
No. Observations:                 200   AIC:                             1221.
Df Residuals:                     198   BIC:                             1227.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         12.3514      0.621     19.876      0.0

In [47]:
#juntando las tres variables independientes (TV, radio, newspaper) en una sola matriz, y luego agregando la constante
# Primero, apilamos horizontalmente las variables
X = np.hstack((TV, Radio, NP))
# Luego, agregamos una única columna constante a la matriz combinada X
X = sm.add_constant(X)
model=sm.OLS(y, X) # -> Modela minimos cuadrados ordinarios con todas las variables
results=model.fit() #-> Optimiza
print(results.summary()) # -> imprime resultados

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Tue, 03 Feb 2026   Prob (F-statistic):           1.58e-96
Time:                        19:53:03   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.0

¿Qué diferencias puedes observar entre los *p-values* de una regresión múltiple y los encontrados en las regresiones simples? ¿Por qué crees que existen estas diferencias?

Podemos observar que el p-value de newspaper tiene una discrepancia importante, esto se debe a que al analizarlo sin los demás, le falta información importante que nos indica que si sirve, sin embargop, al analizar todo junto, nos damos cuenta que en realidad lo que se vendio de newspaper es dependiente con radio y tv, y por lo tanto, es 86% probable que haya sido suerte lo que nos dio.

## Referencia

James, G., Witten, D., Hastie, T., Tibshirani, R.,, Taylor, J. (2023). An Introduction to Statistical Learning with Applications in Python. Cham: Springer. ISBN: 978-3-031-38746-3

## Addendum

Para calcular los *p-values* de los parámetros sin `statsmodels`:
1. Calcular RSS
2. Calcular RSE
3. `var_beta = np.linalg.inv(X.T @ X) * rse**2` (X con columna de intercepto)
4. `std_beta = np.sqrt(var_beta.diagonal())` El orden de los valores corresponde al orden de los factores en las columnas de la matriz $X$.
5. Calcular *estadístico t*
6. Calcular *p-value*